services:
  app:
    container_name: app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"    
      - "443:443"  
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data        
      - caddy_config:/config    
    depends_on:
      - app
    networks:
      - app-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
