// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InfraStructure is an autogenerated mock type for the InfraStructure type
type InfraStructure struct {
	mock.Mock
}

// UUID provides a mock function with given fields:
func (_m *InfraStructure) UUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ValidateStruct provides a mock function with given fields: s
func (_m *InfraStructure) ValidateStruct(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ValidateStruct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInfraStructure creates a new instance of InfraStructure. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfraStructure(t interface {
	mock.TestingT
	Cleanup(func())
}) *InfraStructure {
	mock := &InfraStructure{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
